# pytorch_lightning==2.0.2
trainer:
  accelerator: gpu
  devices: 1
  precision: 16-mixed
  logger:
    class_path: pytorch_lightning.loggers.CSVLogger
    init_args:
      save_dir: output
      name: swin
  max_steps: 5000
  val_check_interval: 100
model:
  model_name: "swin"
  training_mode: lora
  optimizer: sgd
  lr: 0.05
  momentum: 0.9
  weight_decay: 0.0
  scheduler: plateau
  warmup_steps: 500
  lora_r: 8
  lora_alpha: 8



  min_lr: 1e-6
  threshhold: 1e-4
  patience: 5
  cooldown: 0
  factor: 0.5
data:
  dataset: cifar100
  root: data/
  size: 224
  batch_size: 128
  workers: 4
model_checkpoint:
  filename: best-step-{step}-{val_acc:.4f}
  monitor: val_acc
  mode: max
  save_last: true
