name: flowers102
accelerator: gpu
devices: 1
precision: 16
max_steps: 1000
val_check_interval: 100
data:
  dataset: flowers102
  root: data/
  size: 224
  batch_size: 128
  workers: 4
model:
  model_name: vit-b16-224-in21k
  optimizer: sgd
  lr: 0.03
  momentum: 0.9
  weight_decay: 0.0
  scheduler: cosine
  warmup_steps: 100
