# pytorch_lightning==2.0.2
trainer:
  accelerator: gpu
  devices: 1
  precision: 16
  logger:
    class_path: pytorch_lightning.loggers.CSVLogger
    init_args:
      save_dir: output
      name: swin
  max_steps: 30000
  val_check_interval: 100
model:
  model_name: "swin"
  training_mode: lora
  optimizer: sgd
  lr: 0.05
  momentum: 0.9
  weight_decay: 0.0
  scheduler: random_plateau
  warmup_steps: 500
  lora_r: 8
  lora_alpha: 8

  patience: 7
  cooldown: 0
  factor: 0.5
  injection_mode: random
  min_lr: 1e-6
  threshold: 1e-4
data:
  dataset: cifar100
  root: data/
  size: 224
  batch_size: 128
  workers: 4
model_checkpoint:
  filename: best-step-{step}-{val_acc:.4f}
  monitor: val_acc
  mode: max
  save_last: true
